# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModernPluvius.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class EditUI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        desktop = QtWidgets.QDesktopWidget()
        MainWindow.setGeometry(desktop.availableGeometry())
        MainWindow.setMinimumSize(MainWindow.size())
        MainWindow.setStyleSheet("background-color: #1e272e;color: white")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.page_list = QtWidgets.QListWidget(self.centralwidget)
        self.page_list.setMinimumSize(QtCore.QSize(100, 0))
        self.page_list.setMaximumSize(QtCore.QSize(250, 16777215))
        self.page_list.setStyleSheet(
            "background-color:#2c3842;border:none; margin: 0 50 0 0;selection-background-color: red;"
        )
        self.page_list.setObjectName("page_list")
        self.horizontalLayout.addWidget(self.page_list)
        self.main_view = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_view.sizePolicy().hasHeightForWidth())
        self.main_view.setSizePolicy(sizePolicy)
        self.main_view.setMinimumSize(QtCore.QSize(0, 0))
        self.main_view.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.main_view.setStyleSheet("background-color: #2c3842;  margin: 0 50 0 0;")
        self.main_view.setObjectName("label")
        self.horizontalLayout.addWidget(self.main_view)
        self.analysis_list = QtWidgets.QListWidget(self.centralwidget)
        self.analysis_list.setMinimumSize(QtCore.QSize(411, 0))
        self.analysis_list.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.analysis_list.setStyleSheet("background-color: #2c3842; border:none;")
        self.analysis_list.setObjectName("analysis_list")
        self.horizontalLayout.addWidget(self.analysis_list)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1108, 21))
        self.menubar.setStyleSheet(
            "QMenuBar{\n"
            "background-color: #2c3842;\n"
            "}\n"
            "\n"
            "QAction{\n"
            "color:white;\n"
            "}"
        )
        self.menubar.setObjectName("menubar")
        self.menuOpen = QtWidgets.QMenu(self.menubar)
        self.menuOpen.setObjectName("menuOpen")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("background-color: #2c3842")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_File = QtWidgets.QAction(MainWindow)
        self.actionNew_File.setObjectName("actionNew_File")
        self.menuOpen.addAction(self.actionNew_File)
        self.menubar.addAction(self.menuOpen.menuAction())
        self.main_view.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.main_view.setText(_translate("MainWindow", ""))
        self.menuOpen.setTitle(_translate("MainWindow", "File"))
        self.actionNew_File.setText(_translate("MainWindow", "Open File"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = EditUI()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
